name: rummideck
description: "Flame 게임 템플릿. 터치로 플레이어 이동 샘플."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  easy_localization: ^3.0.7+1
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  flame: ^1.35.1
  go_router: ^17.1.0
  flame_audio: ^2.11.14
  get_storage: ^2.1.1
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/audio/sfx/
    - assets/audio/music/
    - assets/fonts/
    - assets/translations/
    - assets/translations/data/en/
    - assets/translations/data/ko/
    - data/common/

  fonts:
    - family: HUAngduIpsul140
      fonts:
        - asset: assets/fonts/HU앵두입술140.otf
